### PR TITLE
Fixed Issue #299

### PR DESCRIPTION
**Pull request by amit-webkul**
Fixed Issue #299

### CODE REVIEW

**Comment by mukulsharma-webkul** [comment]
not working, Getting an error when trying to update the channel. Kindly take the reference from the video below.

https://jam.dev/c/21259f74-873b-417f-9ed0-dce651c974e0

**Comment by amit-webkul** [comment]
@mukulsharma-webkul,

Please run the command for swagger documentation update. Just because I have updated the code in swagger documentation.
`php artisan l5-swagger:generate --all`

**Comment by mukulsharma-webkul** [comment]
channel is updated but while opening the channel getting exception, kindly take the reference from the video below.

https://jam.dev/c/0dccfe74-9df5-4acd-a594-22e19743c6c9

**Comment by mukulsharma-webkul** [comment]
verified, working fine.

https://jam.dev/c/1f9441cb-5b0a-4b59-bc41-5fb84866c80f

**Pull request merged**
